Repository BSA-US/primer, pull requests merged in 2020-06, with the labels that each got.

#20 modularize store
  src/components/index.js
  src/components/visualizations/DualPowerProject.vue
  src/components/visualizations/index.js
  src/store/index.js
  src/store/visualizations/dual-power-project.js
  src/store/visualizations/index.js
  src/views/Home.vue
Labels: :sparkles: optimization

#26 add step filter
  api/config.js
  src/components/Filter.vue
  src/components/visualizations/DualPowerProject.vue
  src/store/visualizations/dual-power-project.js
  src/views/Home.vue
Labels: :sparkles: feature

#25 Fix for #23
  src/components/visualizations/DualPowerProject.vue
Labels: :bug: bug

#27 Annotate links
  package.json
  src/components/Filter.vue
  src/components/visualizations/DualPowerProject.vue
  src/store/visualizations/dual-power-project.js
  src/views/Home.vue
  yarn.lock
Labels: :sparkles: feature

#28 add zoom
  package.json
  src/components/Filter.vue
  src/components/visualizations/DualPowerProject.vue
  src/views/Home.vue
  yarn.lock
Labels: :sparkles: feature

#29 fix visualization & make /config truly async
  api/config.js
  src/components/visualizations/DualPowerProject.vue
Labels: :bug: bug, :sparkles: optimization
